### ISSUE TITLE
Add demo gif to README.md

### ISSUE THREAD

**Issue by ripzery** [omisego/pos-client-android#30]
In order to show the main functionality of the app at a glance

**Comment by yoonusc** [comment]
Highly customizable Android-based POS Application source codes written in kotlin ,kotlin is new language for android , it is easy to learn and less coding makes easy to maintain, our Android POS is used modern kotlin codes so you can take advantages of kotlin ,this application have it's own frame work that enables customize easily, this app contains modules like point of sales , purchase,report, stock,shipments..etc, you can manage product, category, customers , vendors , you can share bills and you have flexible options for printing bills like 2 inch , 3 inch thermal pos printers , A4 printers , this app design is also support multi-language,it's highly customizable for your ERP   [http://www.mycodlabs.com/)]( http://www.mycodlabs.com/)
